### PR TITLE
Add `strings`

### PR DESCRIPTION
**Pull request by anttih**

### CODE REVIEW

**Comment by f-f** [comment]
We have two issues in this PR:
1. We are not reporting the right exit code from `purescm run` if we are missing shared libraries or symbols, I suspect we broke the exception handler somewhere?
2. We don't have the newest chez (version 10, we need all its new features) anywhere else than in nixpkgs. We have a few options:
    1. we can compile it from scratch and stash it somewhere, then pull it and use it in CI
    2. same as above, but a whole `.deb` file
    3. just use the same `nix-shell` that we use in the `purescm` repo, but that won't allow us to see if chez is able to use system libraries outside of a nix build

**Comment by anttih** [comment]
> We have two issues in this PR:
> 
>     1. We are not reporting the right exit code from `purescm run` if we are missing shared libraries or symbols, I suspect we broke the exception handler somewhere?

Correct, I broke it. [Here](https://github.com/purescm/purescm/pull/229) is a fix.

**Comment by anttih** [comment]
>     2. We don't have the newest chez (version 10, we need all its new features) anywhere else than in nixpkgs. We have a few options:
>        
>        1. we can compile it from scratch and stash it somewhere, then pull it and use it in CI
>        2. same as above, but a whole `.deb` file
>        3. just use the same `nix-shell` that we use in the `purescm` repo, but that won't allow us to see if chez is able to use system libraries outside of a nix build

I'm fine using the same `nix-shell` here until there is a Chez 10 ubuntu package up.

**Review by f-f — APPROVED** [review]
Wonderful 🙂

**Pull request merged**
